# Generated by Django 3.2.18 on 2023-04-18 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cookbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=200, unique=True)),
                ('approved', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cookbooks', to=settings.AUTH_USER_MODEL)),
                ('recipes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book', to='blog.recipe')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
