# Generated by Django 3.2.18 on 2023-04-18 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_cookbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookbook',
            name='content',
            field=models.TextField(default=''),
        ),
    ]
