# Generated by Django 3.2.18 on 2023-04-18 18:12

import cloudinary.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0004_cookbook_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookbook',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='cookbook',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='book_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
