# Generated by Django 3.2.18 on 2023-04-18 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20230418_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cookbook',
            name='recipes',
        ),
        migrations.AddField(
            model_name='cookbook',
            name='recipes',
            field=models.ManyToManyField(blank=True, related_name='book_likes', to='blog.Recipe'),
        ),
    ]
