# Generated by Django 3.2.18 on 2023-04-18 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_cookbookcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookbook',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0),
        ),
    ]
