# Generated by Django 3.2.18 on 2023-04-19 16:57

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0008_cookbook_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cookbook',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cookbook',
            name='recipes',
            field=models.ManyToManyField(blank=True, related_name='book_recipes', to='blog.Recipe'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='profile_image'),
        ),
    ]
