# Generated by Django 3.2.18 on 2023-04-20 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cookbook',
            name='featured_image',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='content',
            field=models.TextField(verbose_name='recipe details'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='time_to_cook',
            field=models.IntegerField(default=0, verbose_name='time to cook (minutes)'),
        ),
        migrations.DeleteModel(
            name='CookbookComment',
        ),
    ]
