# Generated by Django 3.2.18 on 2023-04-20 21:28

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20230420_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookbook',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
