# Generated by Django 3.2.18 on 2023-04-20 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_cookbook_featured_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='email',
        ),
    ]
